### PR TITLE
Made it use my version of the module so the edits aren't needed

### PR DESCRIPTION
**Pull request by mcao**

### CODE REVIEW

**Comment by clrxbl** [comment]
I feel like a new version is unnecessary since nothing else has changed. You might also want to add a link to the new module for transparency and edit wintools.

**Comment by WalshyDev** [comment]
A new version would be smart, a link would also be nice I think

**Comment by mcao** [comment]
As of a few hours ago, wintools has been patched on the node spotify webhelper. I'll update this PR to reflect that soon.

**Comment by mcao** [comment]
Alright, my module is no longer needed since the only thing you have to do is edit the http thing. I'll bug the dev of that module to merge the pending PR there.

**Comment by mcao** [comment]
This is unneeded as both modules (with some prodding from me) have been fixed.

**Pull request closed without merging**
